### ISSUE TITLE
Upload only if changed

### ISSUE THREAD

**Issue by elcool0r** [titom73/ansible-junos-ztp#31]
Is there any way to change the playbook to only do the upload if the cfg changed? I didnt succed with my little ansible knowledge.
Every time I'm running the ztp config generation the script want's to upload 130 configs and this takes some time.

**Comment by titom73** [comment]
I will try to find a way to do that by using a `notify` method to only generate and push `dhcpd.conf` to the remote system.

Let me come back to you in a couple of days.

Regards,

**Comment by titom73** [comment]
Role now supports synchronize method to sync devices' configuration with FTP servers.

But the problem with `synchronize` module is it relies on `rsync` and you have to configure `ssh-key` between your ansible host and your ftp server or manually enter password for `ansible_ssh_user` during the playbook execution.

So in order to provide more choice, you can enable the use of `rsync`, an extra option is available in the playbook

```
---
  ### Send files to ZTP servers
  - name: Send ZTP configurations & softwares to server
    hosts: ztp-servers
    connection: ssh
    gather_facts: no
    vars:
        sync: true
  [...]
```

And here is an output with `sync=true` set in the playbook:

```
➜  ansible-junos-ztp git:(issue31) ✗ ansible-playbook playbook-ztp-push-data.yml

PLAY [Send ZTP configurations & softwares to server] ***************************

TASK [ztp-push-dhcp : Copy dhcp content to dhcp-server] ************************
ok: [ztp01]

TASK [ztp-push-dhcp : Restart dhcp service to apply changes] *******************
changed: [ztp01]

TASK [ztp-push-dhcp : Push junos configuration to the FTP server with sync] ****
ansible@10.73.1.200's password:
ok: [ztp01]

TASK [ztp-push-dhcp : Push junos configuration to the FTP server] **************
skipping: [ztp01] => (item=/home/tom/scripting/ansible-junos-ztp/conf/FR-EX2200-111.conf)
skipping: [ztp01] => (item=/home/tom/scripting/ansible-junos-ztp/conf/FR-EX2200-110.conf)
skipping: [ztp01] => (item=/home/tom/scripting/ansible-junos-ztp/conf/FR-EX2200-112.conf)

TASK [ztp-push-dhcp : Push junos softwares to the FTP server] ******************

PLAY RECAP *********************************************************************
ztp01                      : ok=3    changed=1    unreachable=0    failed=0
``` 

And result if you change `sync` to `false`:

```
➜  ansible-junos-ztp git:(issue31) ✗ ansible-playbook playbook-ztp-push-data.yml

PLAY [Send ZTP configurations & softwares to server] ***************************

TASK [ztp-push-dhcp : Copy dhcp content to dhcp-server] ************************
ok: [ztp01]

TASK [ztp-push-dhcp : Restart dhcp service to apply changes] *******************
changed: [ztp01]

TASK [ztp-push-dhcp : Push junos configuration to the FTP server with sync] ****
skipping: [ztp01]

TASK [ztp-push-dhcp : Push junos configuration to the FTP server] **************
ok: [ztp01] => (item=/home/tom/scripting/ansible-junos-ztp/conf/FR-EX2200-111.conf)
ok: [ztp01] => (item=/home/tom/scripting/ansible-junos-ztp/conf/FR-EX2200-110.conf)
ok: [ztp01] => (item=/home/tom/scripting/ansible-junos-ztp/conf/FR-EX2200-112.conf)

TASK [ztp-push-dhcp : Push junos softwares to the FTP server] ******************

PLAY RECAP *********************************************************************
ztp01                      : ok=3    changed=1    unreachable=0    failed=0
```

You can make some tests by using branch [issue31](https://github.com/titom73/ansible-junos-ztp/tree/issue31) created for this issue.

**Comment by elcool0r** [comment]
thx. the execution time for 64 files went from 1m12s to 6s.

**Comment by elcool0r** [comment]
to prevent errors with legacy playbooks i would recomment to create the file ztp-push-dhcp/defaults/main.yaml and add "sync: false".

**Comment by titom73** [comment]
Agree. In such way, we have to define sync like below to allow to overwrite default value:
```
---
  ### Send files to ZTP servers
  - name: Send ZTP configurations & softwares to server
    hosts: ztp-servers
    connection: ssh
    gather_facts: no
    roles:
      - {role: ztp-push-dhcp, become: yes, sync: true}
```
