### ISSUE TITLE
ztp-push-dhcp is not looking for the right directory

### ISSUE THREAD

**Issue by titom73** [titom73/ansible-junos-ztp#35]
`ztp-push-dhcp` is not looking for the right directory to push softwares on ZTP server:

* Current implementation:
```
- name: Push junos softwares to the FTP server
  copy: src={{ item }} dest={{ztp.path.ftp_root}}/{{ztp.path.soft}}/{{ item | basename  }}
  with_fileglob:
- "{{ztp.path.software_local}}/*"
```
* Should be:
```
- name: Push junos softwares to the FTP server
  copy: src={{ item }} dest={{ztp.path.ftp_root}}/{{ztp.path.soft}}/{{ item | basename  }}
  with_fileglob:
- "{{build_dir}}/{{ztp.path.software_local}}/*"
```

[Task file](https://github.com/titom73/ansible-junos-ztp/blob/master/roles/ztp-push-dhcp/tasks/main.yaml)
